### ISSUE TITLE
Supporting Fl_RGB_Image depth 1, and 2.

### ISSUE THREAD

**Issue by rageworx** [rageworx/fl_imgtk#17]
I seems to need supporting single Y channel  and  Y+alpha channel ( depth 2 ) of Fl_RGB_Image.
Someone may love this feature for making some special viewer.

* additional ref. https://github.com/rageworx/fl_imgtk/pull/16

**Comment by rageworx** [comment]
# MIOHDR need this too.
* additional ref. https://bitbucket.org/rageworx/make_img_o_hdr/issues/31/supporting-variable-depths-of-png-image

**Comment by rageworx** [comment]
Each different color space merging ...

![image](https://user-images.githubusercontent.com/6948225/119298421-fb789780-bc97-11eb-8b99-af7626aaa6d7.png)

![image](https://user-images.githubusercontent.com/6948225/119298407-f3b8f300-bc97-11eb-8cc6-47ea33714086.png)

@fire-eggs may love this :)

**Comment by rageworx** [comment]
RGB color base on gray image test,
![image](https://user-images.githubusercontent.com/6948225/119298843-c6b91000-bc98-11eb-947b-1ad8e7a9a726.png)

Looks strange background on overwrapped.

**Comment by rageworx** [comment]
re-programmed convert all to RGB and RGBA ... Looks better.

![image](https://user-images.githubusercontent.com/6948225/119305643-f7eb0d80-bca3-11eb-89d8-d0c5f5076ace.png)

**Comment by rageworx** [comment]
Fixed bug, works fine.

color+color( alpha 100 -> 50% )
![image](https://user-images.githubusercontent.com/6948225/119313284-55845780-bcae-11eb-89a5-08d863aeaf6f.png)

gray+color ( alpha 100 -> 50% )
![image](https://user-images.githubusercontent.com/6948225/119313425-81074200-bcae-11eb-820d-52502855bcf7.png)

gray+gray+alpha ( alpha 100 -> 50% )
![image](https://user-images.githubusercontent.com/6948225/119313512-9b412000-bcae-11eb-9461-31da3a277bcb.png)

color+gray+alpha ( alpha 100 -> 50% )
![image](https://user-images.githubusercontent.com/6948225/119313613-b4e26780-bcae-11eb-9566-65377cb5715e.png)

Ok.

**Comment by rageworx** [comment]
Draw line testing on gray ( color works well ),

![image](https://user-images.githubusercontent.com/6948225/119321386-8c12a000-bcb7-11eb-8c28-540d27108c99.png)

Looks good.

**Comment by rageworx** [comment]
Looks almost done.

**Comment by rageworx** [comment]
Commited changes for 7c1ee71..2cf6de0

**Comment by fire-eggs** [comment]
:+1:
