### ISSUE TITLE
[HELP] undefined reference error

### ISSUE THREAD

**Issue by Luciogi** [rageworx/fl_imgtk#21]
even I use in my actual code I get same error
library is compiled using g++

$ cat test.cpp
```
#include "/home/oggy/projects/PicMe/fl_imgtk/lib/fl_imgtk.h"
#include <FL/Fl_PNG_Image.H>
int main(){
  Fl_PNG_Image* img = new Fl_PNG_Image("/home/oggy/Pictures/Square_200x200.png");
  fl_imgtk::rotate90(img);
}
```

$ g++ -lfltk -lfltk_images -std=c++11  -L /home/oggy/projects/PicMe/fl_imgtk/lib -l fl_imgtk  test.cpp
```
/usr/bin/ld: /tmp/ccVPeWoH.o: in function `main':
test.cpp:(.text+0x3e): undefined reference to `fl_imgtk::rotate90(Fl_RGB_Image*)'
collect2: error: ld returned 1 exit status
```

**Comment by fire-eggs** [comment]
Show us the output of the command `nm /home/oggy/projects/PicMe/fl_imgtk/lib/fl_imgtk.a | grep "rotate90"`. The symbol must not be visible from the library you're linking against.

Here's my output for reference:
```
kevin@LMintDev1:~/proj/fl_imgtk/lib$ nm libfl_imgtk.a | grep "rotate90"
0000000000003838 T _ZN8fl_imgtk8rotate90EP12Fl_RGB_Image
00000000000000f6 t _ZN8fl_imgtk8rotate90EP12Fl_RGB_Image._omp_fn.0
```

**Comment by fire-eggs** [comment]
Better yet, do `nm -C`, e.g:
```
kevin@LMintDev1:~/proj/fl_imgtk/lib$ nm -C libfl_imgtk.a | grep "rotate90"
0000000000003838 T fl_imgtk::rotate90(Fl_RGB_Image*)
00000000000000f6 t fl_imgtk::rotate90(Fl_RGB_Image*) [clone ._omp_fn.0]
```

**Comment by Luciogi** [comment]
@fire-eggs here is output of `nm -C /home/oggy/projects/PicMe/fl_imgtk/lib/libfl_imgtk.a | grep "rotate90"`
```
00000000 T fl_imgtk::rotate90(Fl_RGB_Image*)
```

**Comment by Luciogi** [comment]
I found, by removing https://github.com/rageworx/fl_imgtk/blob/08edb2bc4cbfb433dc538a3c5c517d52a1a8c98b/Makefile.gcc#L38
fixes problem

**Comment by rageworx** [comment]
Dear @Luciogi ,

> I found, by removing
> 
> https://github.com/rageworx/fl_imgtk/blob/08edb2bc4cbfb433dc538a3c5c517d52a1a8c98b/Makefile.gcc#L38
> 
> fixes problem
> 
> Edit: For `Makefile.llvm` , No idea what is causing issue

I will look for your case, by removing `-Os` and `-s` from makefile.
Thank you !

Dear @fire-eggs ,
Thank you Kevin !

**Comment by rageworx** [comment]
> #include "/home/oggy/projects/PicMe/fl_imgtk/lib/fl_imgtk.h"
> #include <FL/Fl_PNG_Image.H>
> int main(){
>   Fl_PNG_Image* img = new Fl_PNG_Image("/home/oggy/Pictures/Square_200x200.png");
>   fl_imgtk::rotate90(img);
> }

Dear @Luciogi ,
as right usage is ...
```
#include <FL/Fl_PNG_Image.H>
#include "fl_imgtk.h"

int main(){
  Fl_PNG_Image* img = new Fl_PNG_Image("/home/oggy/Pictures/Square_200x200.png");
  fl_RGB_Image* imgRotated = fl_imgtk::rotate90(img);
  
  // do something ...
  
  delete imgRotated;
  
  // ...
}
```
I hope it could be helpful usage for you.

**Comment by Luciogi** [comment]
@rageworx specifically `-fopenmp` flag is causing problem

**Comment by rageworx** [comment]
Dear @Luciogi ,
Please refer to https://github.com/rageworx/fl_imgtk/issues/22#issuecomment-1614534895.
Looks same question, right ?

**Comment by rageworx** [comment]
Dear @Luciogi ,
Is it also solved for you ?

**Comment by Luciogi** [comment]
Yup, solved
